const HOTSPOTS = {
  PWR: [
    {
      id: "vessel",
      label: "Reactor vessel",
      description: "The vessel holds the core, coolant, and control equipment under high pressure so water stays liquid while it absorbs heat.",
      anchor: [0, 0.35, 0],
      camera: { lookAt: [0, 0.35, 0], offset: [1.2, 0.8, 1.4] },
    },
    {
      id: "fuel-bundles",
      label: "Fuel bundles",
      description: "These tightly packed fuel rods generate heat from fission and are the heart of the reactor core.",
      anchor: [0, -0.2, 0],
      camera: { lookAt: [0, -0.2, 0], offset: [0.9, 0.7, 1.1] },
    },
    {
      id: "control-rods",
      label: "Control rods",
      description: "Control rods absorb neutrons and help operators raise, lower, or shut down the chain reaction.",
      anchor: [0, 0.95, 0],
      camera: { lookAt: [0, 0.95, 0], offset: [1.0, 0.8, 1.2] },
    },
    {
      id: "steam-generator",
      label: "Steam generator",
      description: "Heat from the primary loop boils a separate water loop here, creating clean steam for the turbine.",
      anchor: [1.95, 0.45, 0.1],
      camera: { lookAt: [1.55, 0.45, 0.05], offset: [1.4, 0.7, 1.2] },
    },
    {
      id: "pressurizer",
      label: "Pressurizer",
      description: "The pressurizer keeps the primary loop at very high pressure so coolant does not flash into steam inside the core.",
      anchor: [0.76, 2.1, 0.64],
      camera: { lookAt: [0.76, 2.0, 0.64], offset: [0.9, 0.7, 1.1] },
    },
  ],
  BWR: [
    {
      id: "vessel",
      label: "Reactor vessel",
      description: "In a BWR, water boils directly inside the vessel, so the reactor itself produces the steam that drives the turbine.",
      anchor: [0, 0.4, 0],
      camera: { lookAt: [0, 0.4, 0], offset: [1.1, 0.8, 1.4] },
    },
    {
      id: "fuel-bundles",
      label: "Fuel bundles",
      description: "Fuel bundles sit low in the vessel where water enters coolest and heats up as it rises through the core.",
      anchor: [0, -0.45, 0],
      camera: { lookAt: [0, -0.45, 0], offset: [0.9, 0.7, 1.1] },
    },
    {
      id: "control-rods",
      label: "Control rods",
      description: "BWR control rods move up from below the core to regulate reactor power and provide shutdown capability.",
      anchor: [0, -1.25, 0],
      camera: { lookAt: [0, -1.1, 0], offset: [1.0, 0.6, 1.0] },
    },
    {
      id: "steam-dryer",
      label: "Steam dryer region",
      description: "Steam separators and dryers remove moisture before steam leaves the vessel for the turbine.",
      anchor: [0, 1.02, 0],
      camera: { lookAt: [0, 1.0, 0], offset: [0.9, 0.8, 1.1] },
    },
    {
      id: "suppression-pool",
      label: "Suppression pool",
      description: "This torus-shaped water pool condenses steam and helps reduce pressure during transients.",
      anchor: [0, -1.62, 0],
      camera: { lookAt: [0, -1.5, 0], offset: [1.4, 0.5, 1.1] },
    },
  ],
  PHWR: [
    {
      id: "calandria",
      label: "Calandria",
      description: "The calandria is the large horizontal vessel that holds the heavy-water moderator around the fuel channels.",
      anchor: [0, 0, 0],
      camera: { lookAt: [0, 0, 0], offset: [1.8, 0.5, 1.3] },
    },
    {
      id: "fuel-channels",
      label: "Fuel channels",
      description: "Pressure tubes carry coolant through the core and let the reactor refuel online while operating.",
      anchor: [0.2, 0.35, 0.35],
      camera: { lookAt: [0.2, 0.35, 0.25], offset: [1.7, 0.5, 1.2] },
    },
    {
      id: "fuel-bundles",
      label: "Fuel bundles",
      description: "Small fuel bundles are loaded inside each pressure tube instead of one large integrated core vessel.",
      anchor: [0, -0.1, -0.2],
      camera: { lookAt: [0, -0.1, -0.2], offset: [1.5, 0.4, 1.2] },
    },
    {
      id: "moderator",
      label: "Heavy-water moderator",
      description: "Heavy water slows neutrons efficiently, which lets PHWR designs use natural uranium fuel.",
      anchor: [0, 0, 0.8],
      camera: { lookAt: [0, 0, 0.6], offset: [1.8, 0.5, 1.4] },
    },
    {
      id: "fuel-machine",
      label: "Fueling machine",
      description: "Refueling machines dock to the channel ends and swap fuel bundles without shutting the reactor down.",
      anchor: [2.65, 0.9, 0],
      camera: { lookAt: [2.25, 0.85, 0], offset: [1.0, 0.4, 0.9] },
    },
  ],
  VVER: [
    {
      id: "vessel",
      label: "Reactor vessel",
      description: "The VVER vessel houses the core much like a PWR, but the reactor system is arranged around horizontal steam generators.",
      anchor: [0, 0.35, 0],
      camera: { lookAt: [0, 0.35, 0], offset: [1.1, 0.7, 1.3] },
    },
    {
      id: "fuel-assemblies",
      label: "Fuel assemblies",
      description: "Hexagonal fuel assemblies pack the core into a compact layout that is characteristic of VVER designs.",
      anchor: [0, -0.05, 0],
      camera: { lookAt: [0, -0.05, 0], offset: [0.9, 0.6, 1.0] },
    },
    {
      id: "control-rods",
      label: "Control rods",
      description: "Control rods insert from the top to shape reactor power and quickly stop the reaction when needed.",
      anchor: [0, 1.05, 0],
      camera: { lookAt: [0, 1.0, 0], offset: [1.0, 0.8, 1.0] },
    },
    {
      id: "steam-generator",
      label: "Horizontal steam generator",
      description: "Unlike Western PWRs, VVER plants commonly use horizontal steam generators arranged around the vessel.",
      anchor: [2.0, 0.18, 0.15],
      camera: { lookAt: [1.7, 0.18, 0.12], offset: [1.2, 0.5, 1.1] },
    },
    {
      id: "containment",
      label: "Double containment",
      description: "The layered containment helps isolate the reactor system and is a visible part of modern VVER layouts.",
      anchor: [1.7, 1.3, 0],
      camera: { lookAt: [1.4, 1.1, 0], offset: [1.4, 0.8, 1.3] },
    },
  ],
  SMR: [
    {
      id: "integrated-vessel",
      label: "Integrated vessel",
      description: "This compact vessel combines core, steam generation, and primary loop functions in one module.",
      anchor: [0, 0.35, 0],
      camera: { lookAt: [0, 0.35, 0], offset: [0.95, 0.75, 1.0] },
    },
    {
      id: "fuel-bundles",
      label: "Fuel bundle region",
      description: "The fuel sits in a tighter, shorter core than a large conventional reactor, which supports modular construction.",
      anchor: [0, -0.42, 0],
      camera: { lookAt: [0, -0.42, 0], offset: [0.85, 0.65, 0.95] },
    },
    {
      id: "cooling-water",
      label: "Passive cooling water",
      description: "The surrounding water inventory helps remove heat even if active systems are unavailable.",
      anchor: [0.9, 0.2, 0.2],
      camera: { lookAt: [0.8, 0.2, 0.1], offset: [1.0, 0.7, 1.0] },
    },
    {
      id: "annular-steam-generator",
      label: "Annular steam generator",
      description: "The ring-shaped steam generator wraps around the vessel internals to keep the reactor module compact.",
      anchor: [0, 0.62, 0],
      camera: { lookAt: [0, 0.62, 0], offset: [0.9, 0.7, 0.95] },
    },
  ],
  Other: [
    {
      id: "core",
      label: "Core",
      description: "Advanced-reactor cores vary by design, but this central region is where fuel and fission heat are concentrated.",
      anchor: [0, -0.28, 0],
      camera: { lookAt: [0, -0.28, 0], offset: [0.9, 0.7, 1.0] },
    },
    {
      id: "reflector",
      label: "Reflector",
      description: "A reflector bounces neutrons back toward the core to improve efficiency and shape the power profile.",
      anchor: [0.82, -0.25, 0],
      camera: { lookAt: [0.6, -0.25, 0], offset: [1.0, 0.6, 1.0] },
    },
    {
      id: "coolant-loop",
      label: "Primary coolant loop",
      description: "Sodium, gas, or molten salt can carry heat away from the core in advanced-reactor concepts like these.",
      anchor: [1.52, 0.2, 0],
      camera: { lookAt: [1.2, 0.2, 0], offset: [1.2, 0.7, 1.1] },
    },
    {
      id: "heat-exchanger",
      label: "Heat exchanger",
      description: "Heat exchangers move energy from the reactor coolant into a secondary system for power production or industrial heat.",
      anchor: [1.45, 0.15, 0.2],
      camera: { lookAt: [1.3, 0.15, 0.2], offset: [1.0, 0.6, 1.0] },
    },
    {
      id: "shell",
      label: "Advanced-reactor shell",
      description: "The outer shell represents the vessel and shielding layout typical of compact advanced-reactor concepts.",
      anchor: [1.2, 1.55, 0],
      camera: { lookAt: [1.1, 1.35, 0], offset: [1.2, 0.8, 1.1] },
    },
  ],
};

export function getReactorHotspots(type) {
  return HOTSPOTS[type] || HOTSPOTS.Other;
}
