// Refreshes the site's plant list from IAEA PRIS before every build.
//
//   node scripts/sync-plants.mjs            # used by `npm run build`
//   node scripts/sync-plants.mjs --lookup   # also look up coordinates for new
//                                           # stations and save them (run locally,
//                                           # then commit src/data/plantCoords.json)
//
// Writes src/data/plants.generated.js (what the app imports) and
// public/data/plants-meta.json (station summary the daily cron diffs against).
// If PRIS is unreachable the committed generated file is kept, so a build
// never fails or ships an empty globe because of an outage.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CURATED_PLANTS } from "../src/data/plantsCurated.js";
import { fetchPrisReactors, fetchPrisWorldStats, groupStations, mergePlants, summarizeStations } from "../api/_lib/plantRegistry.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const COORDS_PATH = join(ROOT, "src/data/plantCoords.json");
const OUT_PATH = join(ROOT, "src/data/plants.generated.js");
const META_PATH = join(ROOT, "public/data/plants-meta.json");
const WIKI = "https://en.wikipedia.org/w/api.php";
const UA = { "user-agent": "NuclearPulseBot/1.0 (+https://thenuclearpulse.com; support@thenuclearpulse.com)" };

const readJson = (path, fallback) => {
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return fallback; }
};

// Finds a station's Wikipedia article and its coordinates.
async function lookupCoords(station) {
  const query = `${station.base} nuclear power plant ${station.country}`;
  const search = await fetch(`${WIKI}?action=query&list=search&srsearch=${encodeURIComponent(query)}&srlimit=3&format=json`, { headers: UA }).then((r) => r.json());
  for (const hit of search?.query?.search || []) {
    if (!/nuclear|power|atomic/i.test(hit.title)) continue;
    const page = await fetch(`${WIKI}?action=query&prop=coordinates&titles=${encodeURIComponent(hit.title)}&format=json`, { headers: UA }).then((r) => r.json());
    const coord = Object.values(page?.query?.pages || {})[0]?.coordinates?.[0];
    if (!coord) continue;
    const name = hit.title.replace(/\s+(Nuclear|Atomic)\s+(Power\s+)?(Plant|Station|Generating Station|Power Station).*$/i, "").trim();
    return { name, lat: Math.round(coord.lat * 100) / 100, lng: Math.round(coord.lon * 100) / 100, wiki: hit.title };
  }
  return null;
}

async function main() {
  const lookup = process.argv.includes("--lookup");
  let reactors;
  let world;
  try {
    [reactors, world] = await Promise.all([fetchPrisReactors(), fetchPrisWorldStats()]);
  } catch (error) {
    console.warn(`[plants] PRIS unavailable (${error.message}); keeping the committed plant list.`);
    return;
  }

  const stations = groupStations(reactors);
  const coords = readJson(COORDS_PATH, {});
  let { plants, unmatchedCurated, missingCoords } = mergePlants(CURATED_PLANTS, stations, coords);

  if (lookup && missingCoords.length) {
    for (const key of missingCoords) {
      const found = await lookupCoords(stations.get(key)).catch(() => null);
      if (found) coords[key] = found;
      console.log(`[plants] ${found ? "found" : "NOT FOUND"}: ${key}${found ? ` -> ${found.wiki} (${found.lat}, ${found.lng})` : ""}`);
    }
    writeFileSync(COORDS_PATH, `${JSON.stringify(coords, null, 2)}\n`);
    ({ plants, unmatchedCurated, missingCoords } = mergePlants(CURATED_PLANTS, stations, coords));
  }

  const updatedAt = new Date().toISOString();
  const counts = { operating: 0, construction: 0 };
  for (const r of reactors) {
    if (r.statusName === "Operational") counts.operating += 1;
    else if (r.statusName === "Under Construction") counts.construction += 1;
  }

  writeFileSync(OUT_PATH, `// Generated by scripts/sync-plants.mjs from IAEA PRIS + src/data/plantsCurated.js.\n// Do not edit by hand; edit the curated list or plantCoords.json instead.\n\nexport const PLANTS_UPDATED_AT = ${JSON.stringify(updatedAt)};\n\nexport const PRIS_REACTOR_COUNTS = ${JSON.stringify(counts)};\n\nexport const PRIS_WORLD_STATS = ${JSON.stringify(world)};\n\nexport const NUCLEAR_PLANTS = ${JSON.stringify(plants, null, 1)};\n`);

  mkdirSync(dirname(META_PATH), { recursive: true });
  writeFileSync(META_PATH, JSON.stringify({ updatedAt, counts, world, stations: summarizeStations(stations) }));

  console.log(`[plants] ${plants.length} plants (${reactors.length} PRIS reactors; ${counts.operating} operating, ${counts.construction} under construction).`);
  if (unmatchedCurated.length) console.log(`[plants] curated-only (not in PRIS): ${unmatchedCurated.join(", ")}`);
  if (missingCoords.length) console.warn(`[plants] ${missingCoords.length} live PRIS station(s) without coordinates, not on the globe: ${missingCoords.join(", ")}`);
}

await main();
